doc/retrace-server.texi, src/lib/retrace.py
Retrace Server's repos are unfortunately still required for setting up the mock environment.
=> Better integration with FAF

doc/retrace-server.texi, src/config/retrace-server.conf, src/lib/retrace.py, src/lib/retrace_worker.py, src/retrace-server-cleanup, src/retrace-server-worker
Resolves https://bugzilla.redhat.com/show_bug.cgi?id=1082376
=> Script hooks

src/Makefile.am, src/config/retrace-server.conf, src/manager.wsgi, src/manager.xhtml, src/manager_usrcore_task_form.xhtml, src/manager_vmcore_task_form.xhtml
Requested by our users. Userspace core support does not work well (yet).
=> Be able to disable "coredump" task in the manager

src/bt_filter
Change license address
Signed-off-by: Patrik Helia <phelia@redhat.com>
=> Change license address

src/lib/retrace.py
Updated pull request containing "best effort" chmod / chgrp - not sure how I missed that originally, guess I was too tired to notice.
=> Rhbz1313011 fix group perms

src/plugins/fedora.py
All Fedora releases adopted Fedora Variants structure.
Signed-off-by: Jakub Filak <jfilak@redhat.com>
=> Correct paths to Fedora development releases

src/retrace/retrace.py
When python script fails, into backtrace file another information are
added. Specifically py-bt, py-locals and py-list.
=> Add python backtrace, source and locals into backtrace

src/retrace-server-cleanup
=> Change error message in cleanup script

src/retrace-server-reposync-faf, src/retrace/config.py.in, src/retrace/retrace.py, src/retrace/retrace_worker.py
This is set of small fixes.
Each problem is described in the commit message, which fixes it.
Signed-off-by: Matej Marusak mmarusak@redhat.com
=> Small fixes

autogen.sh
Signed-off-by: Matej Marusak <marusak.matej@gmail.com>
=> Improve autogen to list and install dependencies

src/stats.wsgi
Installing RS on new machine I discovered there were some bugs on stats page.
See commit messages to learn more about them.
=> Fixes on stats page

src/retrace/retrace_worker.py
The process of retracing can fail. That meant that sometimes tmpdir
created from faf-c2p was not removed.
The _fail method was called at least twice, between creating and
deleting this tmpdir. Also a _fail method could be called from different
function that was called between creating and deleting tmpdir.
Therefore I've decided to put fafrepo as class attribute, so it is
possible to delete from anywhere.
=> Cleanup tmp FAF repository after failing

retrace-server.spec.in, src/Makefile.am, src/retrace-server-task, src/retrace-server-task.txt
This commit implements commandline client for creating, getting and
setting tasks.
=> Add commandline client

src/retrace/retrace.py
HOWEVER: we are not able to tell from package name its epoch. This is not problem when using FAF packages. It could be when two packages with same name, version and release are in the same OPSYS release and FAF packages are not used. (It does not break anything, only does not fix entirely the whole problem).
=> Enable packages with epoch

src/retrace/retrace_worker.py
The only place start_vmcore is called from is the start method of
RetraceWorker, and that call is inside a try ... except clause which
calls _fail in the 'except' part.  Thus, inside start_vmcore, if we
have a nested exception, we don't need to call _fail there.  Instead
we should just raise an exception and let the 'start' method call
_fail with our Exception string set to the describe the failure.
This patch also adds an error message if mock is being used and
prepare_debuginfo or one of the crash commands fail.  This makes
it consistent with the non-mock case.  Once we move this except
clause un-indent the rest of the block to make it consistent.
=> Remove duplicate RetraceWorker._fail call when start_vmcore fails

src/retrace/retrace.py
This is a resubmit of pull request #174 with all changes made.
=> Rhbz1535592 rhbz1440381 kernelver parser bz1540253 crash osrelease spin final v2

src/bt_filter, src/retrace/retrace.py, test/run_test.py
Fix of missing, bad or trailing whitespaces identified by python-modernize and pylint tools.
=> Refactoring: Missing or bad whitespace

src/retrace-server-interact, src/retrace/plugins.py, src/retrace/retrace.py
The syntax for raising exceptions changed between Python 2 and Python 3.
=> py3 compatibility: Adjust raise statement syntax

src/retrace-server-reposync, src/retrace/retrace.py, test/run_test.py
=> Clean up of unused imports

src/retrace/retrace.py, src/retrace/retrace_worker.py, test/run_test.py
=> Adjust indentation according to pylint recommendation

retrace-server.spec.in
See
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/MP2QVJZBOJZEOQO2G7UB2HLXKXYPF2G5/
=> do not require install-info on F28+

src/ftp.wsgi, src/index.wsgi, src/manager.wsgi, src/plugins/fedora.py, src/retrace-server-bugzilla-query, src/retrace-server-cleanup, src/retrace-server-interact, src/retrace-server-worker, src/retrace/retrace.py, src/retrace/retrace_worker.py
Fix of too long lines (longer than 120 characters) and missing whitespaces.
=> Refactoring: Too long lines, missing whitespaces

docker/Dockerfile, docker/Dockerfile_local, docker/Makefile, docker/files/plugins/fedora.py, docker/files/usr/bin/retrace-server-entrypoint, docker/files/usr/bin/run_retrace_server, docker/files/usr/libexec/fix-permissions
This is not for production use, mostly for development.
=> Introduce Docker

src/retrace-server-reposync
=> reposync: Inform why creating of repository failed

src/retrace/retrace.py, src/retrace/retrace_worker.py
=> A couple of fixes

retrace-server.spec.in
=> spec: Fix test condition for Fedora

src/retrace/retrace_worker.py
- Fix typo in function name
- Remove unused function
- Add string formating
=> Various fixes for retrace worker

src/create.wsgi
The change was introduce in commit
5223d96c8ba156165b296b1643e2fbdf28bede85
Signed-off-by: Martin Styk <mastyk@redhat.com>
=> create: Fix strip_extra_pages() invocation

DEPLOYING.md, README.md, doc/retrace-server.texi
See commit.  
Signed-off-by: Michal Fabik <mfabik@redhat.com>
=> Fix typos and minor grammar issues

src/retrace-server-interact
Introduced in 69ad6fdba6bef9030a3af7758376fc540f10fd2c
=> retrace-server-interact: Fix undefined self var

doc/retrace-server.texi, src/config/retrace-server.conf, src/create.wsgi, src/retrace/config.py.in, src/retrace/retrace_worker.py
Historical, does not work at the moment.
=> Remove workdir functionality

docker/Dockerfile, docker/Dockerfile_local, docker/Makefile, docker/files/usr/bin/run_retrace_server
=> Make retrace-server in docker functional

README.md
Mostly for CI testing purposes.
=> README.md: Change capitalization of freenode

src/retrace/retrace_worker.py
With repo created in code and copied into container we can save a significant
amount of time because installing dnf-plugins-core took too much time (caching remote metadata).
Old times: ~4-6 minutes (mock ~1:30)
Started:   2020-01-29 16:29:02
Finished:  2020-01-29 16:33:17
New: ~2-4 minutes
Started:   2020-01-29 17:09:08
Finished:  2020-01-29 17:11:20
And also reducing amount of layers (each RUN, COPY command creates a layer) and reordering the commands for caching purposes.
=> podman: Tweak the Dockerfile for retracing

src/plugins/fedora.py, src/retrace/config.py.in, src/retrace/plugins.py, src/retrace/retrace.py, src/retrace/retrace_worker.py
See commits for more.
- Removed never used variables
- Removed redundant else statement
- Fixed implicit concatenation
- Fixed too few parameters for `__setattr__` method
- Removed unnecessary assignment
=> Fix alerts found by LGTM

src/retrace-server-reposync
See commits. Initially, I intended to go the libdnf route for maximum flexibility, but the DNF Python API is somehow less braindead.
I imagine this fixes https://github.com/abrt/retrace-server/issues/321.
=> Make reposync work again

.gitignore, src/plugins/centos.py, src/plugins/rhel.py, src/retrace/hooks/hooks.py, src/retrace/retrace.py
I have amended some type annotations mypy was complaining about and fixed one undefined variable reference.
=> More type annotations

src/retrace/retrace.py
Leftover from https://github.com/abrt/retrace-server/pull/310
Resolves:
https://github.com/abrt/retrace-server/issues/329
Signed-off-by: Michal Fabik <mfabik@redhat.com>
=> Fix '+' operator use with Paths

src/retrace-server-interact, src/retrace/retrace.py
Fixing more fallout from https://github.com/abrt/retrace-server/pull/310, adding type annotations and errors reported by `mypy`.  
Resolves: https://github.com/abrt/retrace-server/issues/336
=> More pathlib fixes

.github/workflows/check.yml, mypy.ini, retrace-server.spec, src/meson.build, src/plugins/meson.build, src/retrace/hooks/meson.build, src/retrace/meson.build
This I would call “going all-in” as far as type annotations go.
Feel free to argue about the configuration.
=> Add GitHub Actions workflow for running code checks

src/retrace-server-cleanup, src/retrace-server-interact, src/retrace-server-reposync-faf, src/retrace/retrace.py, src/retrace/retrace_worker.py
See commits.
Resolves: https://github.com/abrt/retrace-server/issues/342
=> Fix missing import and more pathlib mess

src/retrace/hooks/config.py, src/retrace/hooks/hooks.py, src/retrace/plugins.py, src/retrace/retrace.py, src/retrace/retrace_worker.py, src/retrace/util.py
I started doodling around with type annotations and mypy and accidentally fixed a few more type errors.
=> More type annotations and fixing errors

src/retrace/retrace.py
There were type check errors because some functions were annotated
with types/classes declared later in the code. This commit reorders
the classes as appropriate.
Signed-off-by: Michal Fabik <mfabik@redhat.com>
=> retrace: Fix class declaration order

src/retrace/hooks/hooks.py, src/retrace/retrace.py, src/retrace/retrace_worker.py, src/retrace/stats.py, src/retrace/util.py
This fixes whitespace issues I ran into while reviewing #356 and some other easy ones.  
See commits.
=> Fix some pylint issues

src/retrace/retrace.py, src/retrace/retrace_worker.py, src/retrace/util.py
=> retrace: Handle paths with colons correctly

.tito/releasers.conf
This way you can just 'tito release all' or 'tito release epel'.
@mgrabovsky Can you build it for epel too?
=> add releasers.conf

src/retrace/retrace_worker.py
\+ improve some of the log messages.
=> Fix "not writable" error

src/retrace/retrace_worker.py
=> Fix path to coredump in dockerfile

src/retrace/retrace.py
This should fix some part #394, though apparently not yet completely.
=> Fixes for Podman backend

retrace-server.spec
Add Recommneds for logrotate package.
=> Update specfile: logrotate

README.md
Add a badge for the `check.yml` workflow in GitHub Actions.
=> readme: Add badge for build status

mypy.ini, pylintrc, src/coredump2packages, src/create.wsgi, src/retrace-server-reposync, src/retrace-server-reposync-faf, src/retrace-server-worker, src/retrace/backends/podman.py, src/retrace/config.py.in, src/retrace/plugins.py, src/retrace/retrace.py, src/retrace/retrace_worker.py, src/retrace/util.py
* Proper escaping in regex string using `br"…"`.
* Make Pylint not warn about missing docstrings.
* Rename some variable in order to conform to Pylint rules.
* Some Pythonic code style improvements.
* Add a few type annotations here and there.
* Pass `check=False` explicitly to `subprocess.run()`.
=> Improve code culture

.github/workflows/coverage.yml, codecov.yml, meson_options.txt, test/meson.build
Analyse code coverage using pytest-cov and upload to Codecov for visualization and analysis.
=> Calculate and upload code coverage to Codecov

src/manager.wsgi
Tasks that are created with custom_url pointing at local files
with incorrect permissions will almost immediately fail, leaving
failed tasks and delayed feedback to the user.
Move the permissions check into the __custom__ URL parsing inside
the manager.wsgi file, which is much sooner than where it is
currently done inside download_remote().  Checking permissions
early gives the user early feedback via the http interface,
and we also avoid creating tasks that will immediately fail
due to improper permissions on the file.
=> manager: Add permissions check to custom_url to avoid failed tasks

.github/workflows/check.yml, .github/workflows/codeql.yml, .github/workflows/coverage.yml
- Add CodeQL workflow as a replacement for LGTM.com.
- Update the `actions/checkout` action to v3.
=> Update GitHub workflows

retrace-server.spec
See [the wiki][1] for details.
[1]: https://fedoraproject.org/wiki/Changes/SPDX_Licenses_Phase_1
=> Use SPDX format for license field
