abrt/retrace-server

src/status.wsgi
Task has log from the beginning.
Signed-off-by: Richard Marko <rmarko@fedoraproject.org>
=> status: use has_finished_time instead of has_log

src/lib/retrace.py
/manager page returned error 500 because VMCoreTask and UsrCoreTask missed in config variable
Signed-off-by: Patrik Helia <phelia@redhat.com>
=> Add VMCoreTask and UsrCoreTask to config

src/lib/retrace.py, src/lib/retrace_worker.py
Saving mock log into retrace directory and add mock log directory into retrace
directory whitelist because all other files and folders are deleted after task
end.
Signed-off-by: Patrik Helia <phelia@redhat.com>
=> Mock logging into retrace task's dir

src/bt_filter
This small patch to bt_filter was submitted by Steve Johnson and fixes the last task / pid missing in the bt_filter output
=> Fix bt_filter missing last task/PID read if the last line was not blank

src/plugins/Makefile.am, src/plugins/fedora.py, src/plugins/rhel.py, src/stats.wsgi, src/stats.xhtml
Prior to the below commits, the release entries of the stats page were hard-coded to query and present the following releases.
Fedora 15
Fedora 16
Fedora 17
The commits below alter this behaviour to allow the releases to be determined based off of the plugins present. For this process, The Fedora plugin has been refreshed to allow it to determine releases for all of the presently available Fedora releases. At the same time, a Red Hat Enterprise Linux plugin is also present to allow, though it currently does not include repository information to allow it to function with the retrace-server-reposync utility.
=> Updating the stats handling and including a RHEL plugin

src/lib/retrace.py
Epoch should be a number and 0 means it is not set.
https://fedoraproject.org/wiki/Packaging:Guidelines#Use_of_Epochs
https://docs.fedoraproject.org/en-US/Fedora_Draft_Documentation/0.1/html/RPM_Guide/ch09s03.html
=> Allow package names with Epoch

src/coredump2packages
When 'eu-unstrip -n' can find the matching ELF and debug files on
disk given the build-ids it will display them, otherwise it won't.
If it can find the files then it "resolves" the module name on the end,
otherwise the name of the module is file path.
Example:
0x7f248b+0x20d 96030f@0x7f248 - - /usr/lib64/gedit/plugins/libtime.so
If the FILE part does not begin with '/' and the MODULE part is not
'[exe]', coredump2packages silently skips these eu-unstrip output
lines ignoring the fact that such lines are completely valid.
This commit ensures that those lines will be processed too.
Signed-off-by: Jakub Filak <jfilak@redhat.com>
=> Correct eu-unstrip parser if FILE is -

src/lib/retrace_worker.py
These minor fixup patches resolves issues with email notifications as described in https://bugzilla.redhat.com/show_bug.cgi?id=1340158
1. Typo causes email notifications to not get sent
2. After fixing typo, duplicate emails get sent for tasks that fail due to unable to determine kernel version
Tested these on a development server with these two patches added on top of retrace-server-1.15-1.el6.noarch
=> Rhbz1340158 email notifications

src/Makefile.am, src/config/retrace-server-httpd.conf, src/ftp.wsgi, src/manager.wsgi, src/manager.xhtml
In the event that UseFTPTasks is enabled, and the backing FTP server
contains an exceptional number of files in it, the resulting query
can take an extreme amount of time to return. In the meantime, the
manager UI is unavailable for use to access existing tasks.
This patch implements an AJAX call to a new "ftp" interface. It will
return the remainder of the "FTP files" table by default, but will
also adhere to the "filter=" variable passing to limit the resulting
table.
Signed-off-by: Kyle Walker <walker.kyle.t@gmail.com>
=> manager.wsgi: Move the FTP query operation to an AJAX operation - Resolves rhbz1124462

src/create.wsgi
Use write() instead of print(), sys.stderr has no print() method.
Signed-off-by: Matej Habrnal <mhabrnal@redhat.com>
=> Fix invalid syntax error in sys.stderr.print()

src/config/retrace-server-httpd.conf
Without this patch httpd refuses to download exploitable file.
On server the following message appears:
H01630: client denied by server configuration: /usr/share/retrace-server/exploitable.wsgi
And 403 is returned.
After creating this patch exploitable was returned correctly.
=> Add "exploitable" into LocationMatch in the httpd.conf

src/coredump2packages
While working with retrace-server I noticed, that sometimes coredump2packages returns less packages for very similar coredumps. Investigating this behaviour I found 2 problems.
1.  Packages with different architectures were marked as duplicity. Later one of them got deleted and often the one with architecture we wanted. Therefore it would be better to keep them both.
2. The eu-unstrip function returns different results based on ability to find ELF image. One of the cases is that FILE is set to '.' and MODULENAME is set to a file path. This case was ignored, even though that MODULNAME provides enough data.
=> Fix coredump2packages

src/plugins/fedora.py, src/plugins/rhel.py, src/retrace/retrace.py, src/retrace/retrace_worker.py
Use argument -ascending in gdbs "thread apply all" so the crashing thread is
depicted first.
Closes abrt/retrace-server#77.
=> Add '-ascending' argument to gdb

retrace-server.spec.in, src/Makefile.am, src/retrace-server-reposync, src/retrace-server-reposync-faf
In faf there was introduced a way of assigning operating system with release
to builds. That makes it possible to find all builds of specific operating
system and release. Then repository can be created by using packages from faf
repository.
Action of creating repository from faf was integrated into
retrace-server-reposync, so when this action is executed and UseFafPackages
in configuration file is enabled, repository is created/updated from faf.
This closes abrt/retrace-server#115.
=> Enable creating repository from faf repository

src/manager.wsgi, src/retrace/retrace.py
I am not sure why but a task on our server was missing finish task file.
I should have looked for the root cause but I believe retrace-server
should recover from it anyway.
I have decided to replace initialize variables requiring contents of
start/finish task files with ctime/mtime of the task directory. These
values looks like the most natural replacements for the missing values
which still makes sense.
Close #113.
Signed-off-by: Jakub Filak <jfilak@redhat.com>
=> Recover from missing start/finish task files

README
There were changes in plugin structure in both 9b6ca7a and 10d8490 but the
README was not updated.
Closes abrt/retrace-server#132
=> Update documentation of plugin in README

retrace-server.spec.in, src/Makefile.am, src/retrace-server-plugin-checker
There was no easy way, how to check if mirrors for repositories were correct.
This commit introduces new action, that can distinguish between accessible and
not accessible mirrors in plugin. Also it can list all mirrors that are currently
accessible (or not accessible).
Closes abrt/retrace-server#109
=> Add plugin checking action

src/retrace/retrace_worker.py
The kernel log contains an oops message which is printed with hex offsets.
For consistency, output in hex when running crash commands involving backtraces.
Use the "set hex" command inside crash to ensure the best backward compatibility
with crash versions.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1416086
=> Default to hex mode for crash commands involving backtraces.

src/config/retrace-server-httpd.conf
Moving WSGIProcessGroup directive to LocationMatch will let retrace
process operate just within specified paths.
=> Change retrace-server httpd config

src/index.wsgi
In 99ad409 there was introduced a typo that caused index page of retrace-server
not working. This commit fixes the problem.
=> Fix character escape typo

src/config/retrace-server.conf, src/manager.wsgi, src/manager_usrcore_task_form.xhtml, src/manager_vmcore_task_form.xhtml, src/managertask.xhtml, src/retrace/config.py.in, src/retrace/retrace.py
This commit adds option for users to see md5sum of original archive. User can
select before submitting task whether this information will be displayed or not.
If selected, this information is displayed on summary page as well as is written
into file. Format of this file is same as when md5sum command is run, so these
data can be compared easily (for example with diff).
Also into configuration file new item was added, to have this checkbox checked
by default.
=> Include md5sum of original archive in summary page

src/manager.wsgi
Typo results in the following error in /var/log/httpd/error_log when
a non-ftp task is submitted through "Custom core location":
mod_wsgi (pid=23919): Exception occurred processing WSGI script '/usr/share/retrace-server/manager.wsgi'.
File "/usr/share/retrace-server/manager.wsgi", line 406, in application
starttime_str = "<tr><th>Started:</th><td>%s</td></tr>" % datetime.datetime.fromtimestamp(starttime)
UnboundLocalError: local variable 'starttime' referenced before assignment
=> Fix typeo in manager.wsgi which creates a backtrace on non-ftp tasks.

src/retrace-server-reposync-faf
Default names of releases differ between FAF and RetraceServer.
It means that running (with UseFafPackages = 1):
`retrace-server-reposync fedora 25 x86_64` will succeed in RS but fail in FAF
`retrace-server-reposync Fedora 25 x86_64` will succeed in FAF but fail in RS
After this patch the first version succeeds in both components.
=> Add aliases into FAF reposync

src/retrace-server-reposync
Sometimes someone does something bad to repo files and directories and
rsync's output seems to be the best source for fixing such problems.
This commit adds possibility to pass more '-v' on command line. If there
are more 2 or more '-v's, then output of executed commands (rsync,
createrepo) is forwarded to stdout/stderr; otherwise the output goes to
/dev/null.
Signed-off-by: Jakub Filak jfilak@redhat.com
=> Make the reposync tool more verbose if required

retrace-server.spec.in, src/retrace/retrace_worker.py
Since mock-1.4.1, BindMount plugin is required to make directories available
for baseurl=file://.
https://github.com/rpm-software-management/mock/wiki#using-file-urls-in-configs
And use DNF in mock configuration on Fedora.
=> Update mock configuration

src/bt_filter, src/coredump2packages, src/ftp.wsgi, src/manager.wsgi, src/retrace-server-cleanup, src/retrace-server-interact, src/retrace-server-plugin-checker, src/retrace-server-reposync, src/retrace-server-reposync-faf, src/retrace-server-worker, src/retrace/argparser.py, src/stats.wsgi
Scripts should explicitly use /usr/bin/python[23] in shebangs.
See https://pagure.io/packaging-committee/issue/698
Also https://fedoraproject.org/wiki/Packaging:Python#Multiple_Python_Runtimes
=> Explicitly state python version in shebangs

src/retrace-server-interact, src/retrace/retrace.py, src/retrace/retrace_worker.py
For larger vmcores it is possible that prepare_debuginfo may take a long time.
This is due to various factors such as makedumpfile, as well as how long crash
takes to load when detecting modules as well as running the early commands
such as 'sys'.  Today we are not setting kernelver or vmlinux as early as we
can and as a result, someone waiting to get access to the vmcore either has to
wait excessivly long or do some manual intervention like setting up vmlinux
manually.  Today if someone tries to run 'retrace-server-interact' before all
commands complete in the retrace, they will end up blocking waiting
for the re-detction of the kernelver which can take a very long time (since
it may run strings on the whole file).  This makes no sense since retrace
figures out the kernelver early on as …
=> Set kernelver and vmlinux as soon as possible

src/retrace/retrace_worker.py
This is an improved patchset based on Matej's review and my additional testing. Items fixed:
first patch originally missed a 'self.' on the notify_email_X functions
second patch checks the 'status' variable at the top and sets "succeeded" or "failed" to use later; this also addresses the reordering of STATUS_SUCCESS and STATUS_FAIL
third patch fix help text to use CONFIG["RepoDir"] rather than hardcoded path
FWIW, I also noticed a separate bug when testing this patchset where RetraceWorker._fail method is called twice for failing tasks and so two email notifications are given. This bug has nothing to do with this patchset though and existed before it so I filed https://bugzilla.redhat.com/show_bug.cgi?id=1535485
=> Rhbz1440383 improve email notifications

src/retrace/retrace.py
The previous commit 232ff36 introduced a minor bug when processing
a vmcore that failed a permission check or read error.  The retrace_log
will show a message indicating 'IOerror' not being defined.
For example:
2018-02-28 15:17:51 prepare_debuginfo failed: global name 'IOerror' is not defined
2018-02-28 15:17:51 File '/retrace/tasks/875129564/crash/vmcore' is not group readable and chmod failed. The process will continue but if it fails this is the likely cause.
While the overall error message is still accurate, there is a small bug
here.  Indeed "IOerror" is not defined and this is a simple typo and this
should be 'OSError'.
Fixing this shows a slightly more accurate retrace_log:
2018-02-28 15:24:38 prepare_debuginfo failed: [Errno 13] Permission denied: …
=> Fix typo in exception handling of get_kernel_release

src/retrace-server-cleanup, src/retrace/retrace.py, src/retrace/retrace_worker.py
Today retrace-server allows the same ftp vmcore to be submitted multiple times.
This means disk space can be consumed for the same vmcore / multiple tasks.
In our production system, we have seen where this may take up around 10% of the
space, or 4TB so it is not insignificant.  To eliminate this overhead,
introduce dedup_vmcore method to RetraceTask.
The dedup_vmcore method takes advantage of the fact we usually have the
md5sum of a downloaded file prior to processing it.  While this md5sum
is not the same as the md5sum of the vmcore, the ending vmcore file after
all processing should always be the same if the same archive is submitted
twice (anything else is a pathalogical case we don't care about).  Also
we can do a simple 'size' check and if the md5sum is the same and the size
is the …
=> Add dedup_vmcore to RetraceWorker and call from retrace-server-cleanup

src/retrace/retrace.py
The md5sum is calculated as soon as a file is downloaded but it is not
written to the file until after the task is processed.  As far as I
can tell the reason for this is due to the fact that multiple files
can in theory be inside the 'downloaded' file.  However, this leads to
the side-effect that a failed task may never write out the md5sum file
with the actual md5sum despite the fact it has been calculated.
Instead the only thing that remains in the file is "Enabled" which is
obviously not desireable.
Fix this by writing the md5sum as soon as it is calculated.  This may
lead to the file being written multiple times but this should not be
a problem.  Also in many instances (for example with vmcores) there is
only one file so it will only be written once.
NOTE: This problem was more …
=> Set md5sum as soon as possible.

src/bt_filter, src/retrace-server-plugin-checker, src/retrace/plugins.py
All `print` statements are replaced with a `print()` function to be compatible with Python 3.
=> py3 compatibility: print statement is replaced with a print() function

src/retrace-server-cleanup
1. Python 3 uses `as` keyword after the exception type where comma is used in Python 2.
2. Clean-up of unused exception value.
=> py3 compatibility: try-except statement

retrace-server.spec.in, src/Makefile.am, src/config/retrace-server.conf, src/manager.wsgi, src/manager.xhtml, src/managertask.xhtml, src/retrace-server-bugzilla-query, src/retrace-server-bugzilla-refresh, src/retrace-server-interact, src/retrace-server-task, src/retrace-server-task.txt, src/retrace/config.py.in, src/retrace/retrace.py
The field is to be filled with bugzilla numbers. This should help to create
an association between task and bugzilla bugs.
The field is used by these tools:
retrace-server-bzquery:
Query bugzilla for trigger words. For found tasks fill the bugzilla field
with bugzilla number.
retrace-server-bugzilla-cleanup:
Look for tasks with bugzilla field filled in and check the status
of entered bugzilla bugs. Refresh ones with open bugzilla bugs.
=> Add bugzilla field and related tools

src/bt_filter, src/retrace/plugins.py
In Python 2, dictionaries had a `has_key()` method to test whether the dictionary had a certain key. In Python 3, this method no longer exists and the `in` operator should be used.
=> py3 compatibility: Replacement of 'has_key' with 'in'

src/manager.wsgi, src/retrace/retrace_worker.py
`map()` built-in function returns a list on Python 2, but an iterator on Python 3. If the first argument to `map()` is a lambda function, then it is converted to an equivalent list comprehension.
=> py3 compatibility: Ensure map function to return a list

retrace-server.spec.in, src/retrace/retrace.py
`basestring` is an abstract type in Python 2, a superclass for both `str` and `unicode` string types. In Python 3, there is only one string type of `str`. The compatibility is solved by six library.
=> py3 compatibility: Replacement of basestring with six.string_types

src/bt_filter
`sorted()` built-in function builds a new sorted list from an iterable.
=> py3 compatibility: Use 'sorted' built-in function

src/retrace/retrace.py
The new literal syntax for sets is available and preferred in Python 3 (the use of curly braces). It has been backported to Python 2.7.
=> py3 compatibility: Set literals

src/retrace/retrace.py
Replacement of `lambda (a, b): function(a, b)` with `lambda a_b: function(a_b[0], a_b[1])` according to PEP 3113.
=> py3 compatibility: Removal of tuple parameter unpacking

src/retrace/argparser.py
The `StringIO` module is gone in Python 3. Instead, import the `io` module and use `io.StringIO` for text.
=> py3 compatibility: Replace StringIO module with io module

src/retrace/retrace.py
In Python 2, `range()` returns a list, and `xrange()` returns an iterator. In Python 3, `range()` returns an iterator, and `xrange()` doesn’t exist. The compatibility is solved by `six` library.
=> py3 compatibility: Resolution of range and xrange

src/retrace/__init__.py, src/retrace/retrace.py, src/retrace/retrace_worker.py
In Python 3, imports can be either absolute or explicitly relative; implicit relative imports are forbidden.
=> py3 compatibility: Adjust imports

src/ftp.wsgi, src/manager.wsgi, src/retrace-server-plugin-checker, src/retrace/retrace.py, src/start.wsgi
`urllib2` and `urlparse` have been moved to `urllib` in Python 3 and `urllib` has been split up. The `urllib` changes follow an order of imports recommended by `pylint` tool.
=> py3 compatibility: Adjust urllib, urllib2 and urlparse

src/manager.wsgi, src/retrace/retrace.py
In Python 2, `filter(function, iterable)` returns a list and is equivalent
to `[item for item in iterable if function(item)]` if function is not `None`
and `[item for item in iterable if item]` if function is `None`. In Python 3,
the function returns an iterator. The replacement of Python 2 `filter()`
function with a proper equivalent or wrapping a call to `filter()`
with a call to `list()` solves the Python 3 compatibility.
=> py3 compatibility: Replace filter function with a list equivalent

retrace-server.spec.in
The "/usr/lib/python2.7/site-packages/retrace" wasn't owned by anyone.
The %dir directive is not needed because without the "*" we include the
directory and entire tree below it.
https://fedoraproject.org/wiki/Packaging:UnownedDirectories
=> spec: Correct the file ownership

src/retrace/retrace.py
I did not file any bug for these two changes but they are minor fixups related to the md5sum patchset to cover a few corner cases.  This was tested in our development / test retrace-server instance and avoids the problems described in the patch header and not causing any valid dedup to be skipped.
=> Skip tasks with no vmcore or invalid md5sum

src/retrace/retrace.py
The test failed on rawhide (gdb v8.1.50) with error message:
"A syntax error in expression, near `full'."
According to the GDB documentation the correct syntax for backtrace
command is `backtrace [full] n`.
- https://sourceware.org/gdb/onlinedocs/gdb/Backtrace.html
Signed-off-by: Matej Habrnal <mhabrnal@redhat.com>
=> Correct syntax for gdb backtrace command

configure.ac, retrace-server.spec.in, src/retrace-server-cleanup, src/retrace/Makefile.am, src/retrace/config.py.in
Adds a new check to Delete(Failed)TaskAfter procedure to prevent tasks with opened/used vmcore/coredump files from being deleted.
Related: rhbz#1253908
=> cleanup: Add check for opened crash files

src/retrace/retrace.py
The get_kernel_release() function reads binary data and tries to match
regexp strings to find kernel versions.  For Python3 we need the regexps
to thus be byte strings.  Once we've found some match, we're down to
a small character set and we can convert that to a string and strip
any spaces, newline or return characters before returning.
This fixes retrace-server task failures with log entries that look like
this:
2019-03-15 14:09:37 prepare_debuginfo failed: cannot use a string pattern on a bytes-like object
2019-03-15 14:09:37 Stripped size: 32.01 GB
2019-03-15 14:09:37 Makedumpfile took 0 seconds and saved 0.00 B
2019-03-15 14:09:37 Analyzing crash data
2019-03-15 14:09:37 cannot use a string pattern on a bytes-like object
=> Fix get_kernel_release() on Python3

src/retrace/retrace.py
Currently there's a small bug if the release fails to decode on all
parsers.  In this case you will get a cryptic message as follows:
'NoneType' object has no attribute 'decode'
Fix this by checking to see if 'release' exists before trying decode.
=> Fix message and code path when we fail to decode the release of vmcore

src/retrace/retrace.py
Commit 2199ab8 broke module extraction because it did handle the
byte arrary return from run_crash_cmdline properly.
Rather than a string, run_crash_cmdline returns a byte array.  When
we are obtaining the list of module object files to extract from crash's
'mod' command, these should be in the form of strings so we can pass
them to 'cpio'.  The reason for the default byte array return on
run_crash_cmdline is found in the discussion of 7ea86bd:
1) some crash commands (not the 'mod' command) may return non-'utf-8'
characters (for example a command that reads a lot of
memory from a vmcore that may be incomplete or damaged)
2) often we save the output of crash commands to a file so we do not
care necessarily if we have non-'utf-8' characters.
Signed-off-by: Dave Wysochanski …
=> Fix module extraction from kernel-debuginfo

src/retrace/retrace.py
https://docs.fedoraproject.org/en-US/packaging-guidelines/Versioning/#_versioning_prereleases_with_tilde
Resolves: #250
=> retrace: Allow tilde in package names

src/retrace-server-interact, src/retrace/retrace.py, src/retrace/retrace_worker.py
Originally when RetraceTask.use_mock was introducted it was done
alongside the implementation of RetraceTask.crash_cmd.  When crash_cmd
was introduced it was not well understood where we really should set
this and read it.  Also, use_mock was not really well done either.
The right thing to do with crash_cmd and use_mock is only set both of
them once the arch has been properly detected from get_kernel_release.
Create methods get_mock(), set_mock(), and has_mock() to handle whether
mock is configured or not.
This cleans up the code quite a bit and fixes on bug which occurs
when 32-bit cores are run on a 64-bit machine where prepare_debuginfo
would be called twice:
https://bugzilla.redhat.com/show_bug.cgi?id=1536683
=> Clean up handling of mock with x86 vmcores in x86_64 environments

doc/retrace-server.texi, src/config/retrace-server.conf, src/exploitable.wsgi, src/ftp.wsgi, src/manager.wsgi, src/managertask.xhtml, src/retrace/retrace.py, src/retrace/retrace_worker.py
I've been testing these patches and I think they are a good modest change to the hooks interface.  If we stick with a lightweight interface to hooks and provide freedom for a hook script to interface with retrace-server via the existing retrace-server-* commands, the only thing I think we need to change is to give a hook a specific directory to write output (results files).  Note the renaming patch is backward compatible with tasks that have existing 'misc' subdirectory so this should not break anything.
I also thought of exporting the "add_results()" and similar functions to a hook script but I think it might be better to avoid that.
=> Pass results dir to hooks

src/create.wsgi, src/retrace-server-bugzilla-query, src/retrace-server-cleanup, src/retrace-server-interact, src/retrace-server-task, src/retrace-server-worker, src/retrace/retrace.py, src/retrace/retrace_worker.py
This series of patches refactors a number of functions into the new KernelVMcore class, and eliminates some confusing and duplicate logic involving vmcore setup, especially the duplicate calls to prepare_debuginfo which happens on some vmcores.
There are likely further cleanups that can be done on this code but I felt this a fairly good series to move things forward.  I have tested this fairly thoroughly and I do not believe there are any regressions here, but it's always possible some corner case could have been missed.
=> Refactor into KernelVMcore and eliminate duplicate prepare_debuginfo

src/stats.wsgi
It used to display last letter (number) of the key. (ie. fc23 = 3; el7 = 7)
=> stats: Display whole release version

retrace-server.spec.in, src/retrace-server-task
This also explicitly disables mutual authentication, which seems to be
causing issues with redirects to /start and friends.
Context:
https://fedoraproject.org/wiki/Changes/kerberos-in-python-modernization
https://github.com/requests/requests-kerberos/issues/64
https://github.com/pythongssapi/requests-gssapi/issues/12
https://github.com/pythongssapi/requests-gssapi/commit/498da2e55f98847c9eeb698f50ac00a2e252cacd
Fixes https://github.com/abrt/retrace-server/issues/263
Signed-off-by: Ernestas Kulik <ekulik@redhat.com>
=> Switch to requests-gssapi

src/retrace/retrace.py
Introduced in 6173c728b2daa7c92c12947ddd488377ca0efa91
vmcore used to be passed to prepare_debuginfo. The prepare_debuginfo is now a method
of KernelVMcore (the vmcore).
=> retrace: Fix undefined vmcore variable

maint/pull-translations, po/LINGUAS, po/ca.po, po/cs.po, po/da.po, po/de.po, po/en_GB.po, po/es.po, po/fi.po, po/fr.po, po/hu.po, po/id.po, po/it.po, po/nl.po, po/pl.po, po/pt.po, po/pt_BR.po, po/sk.po, po/sv.po, po/tr.po, po/uk.po, po/zh_CN.po, po/zh_TW.po, zanata.xml
Copy-pasted from abrt.
Pulls the translations from fedora.zanata.org/project/view/retrace-server.
Closes #173
=> Add transtalations from Fedora Zanata

src/retrace/retrace_worker.py
Introduced in 9e79d410d9b5a882fa3770f24b78f930def9ab29
The default file mode used to be "write" but it was changed to write raw bytes.
=> retrace_worker: Fix file mode to write to file

retrace-server.spec.in, src/retrace/retrace_worker.py
Introduced in 5a1e21a0f6ca8174a88f4eaf37887100e0ec311b
As `dnf` is  now available on both RHEL(7,8) and Fedora (and with the `--skip-broken` switch support),
we can remove the `distro` "hack".
=> retrace_worker: Remove distro hack from mock config

src/retrace/retrace.py, src/retrace/retrace_worker.py
The old format:
```
2019-11-25 15:08:43 Analyzing crash data
2019-11-25 15:08:43 Hook script failed with exit status 1.
2019-11-25 15:08:44 Preparing environment for backtrace generation
2019-11-25 15:09:29 Generating backtrace
2019-11-25 15:09:37 Cleaning environment after backtrace generation
2019-11-25 15:09:41 Saving crash statistics
2019-11-25 15:09:41 Retrace took 58 seconds
2019-11-25 15:09:41 Retrace job finished successfully
```
The new format:
```
[2019-11-25 15:04:56] [I] Analyzing crash data
[2019-11-25 15:04:56] [E] Hook script failed with exit status 1.
[2019-11-25 15:04:57] [I] Preparing environment for backtrace generation
[2019-11-25 15:05:40] [I] Generating backtrace
[2019-11-25 15:05:47] [I] Cleaning environment after backtrace generation
[2019-11-25 15:05:51] [I] …
```
=> retrace: Change logging format

DEPLOYING.md, configure.ac, doc/retrace-server.texi, docker/Dockerfile, docker/Dockerfile_local, retrace-server.spec.in, src/config/Makefile.am, src/config/hooks/Makefile.am, src/config/hooks/debuginfo.conf, src/config/hooks/environment.conf, src/config/hooks/fail.conf, src/config/hooks/mock.conf, src/config/hooks/retrace.conf, src/config/hooks/start.conf, src/config/hooks/success.conf, src/config/hooks/task.conf, src/config/retrace-server-hooks.conf, src/config/retrace-server.conf, src/retrace/Makefile.am, src/retrace/config.py.in, src/retrace/hooks/Makefile.am, src/retrace/hooks/__init__.py, src/retrace/hooks/config.py, src/retrace/hooks/hooks.py, src/retrace/retrace_worker.py
Instead of specifying what to run for certain a hook in `/etc/retrace-server.conf`
you will be able to put executable scripts into one of the hook directories in
`/usr/share/retrace-server/hooks/{start,fail,success,...}` and
retrace-server worker will run all the executable scripts it finds.
The directory can be changed with HookDir in `/etc/retrace-server/retrace-server-hooks.conf`.
For now you can configure `timeout` and `cmdline` options for the hooks.
Example for a `success` hook:
$ ls /usr/share/retrace-server/hooks/success/
/usr/share/retrace-server/hooks/success/echo
$ cat /etc/retrace-server/hooks/success.conf
```
[success]
timeout = 42
[success.echo]
cmdline = {taskid}
```
retrace-server worker will now run `echo 4321` with timeout of 42 seconds
once some retrace task finishes …
=> Change of retrace hooks

retrace-server.spec.in, src/config/hooks/Makefile.am
Commit 83327af missed a couple changes that caused the following build
errors:
make[8]: Entering directory '/root/git/retrace-server/src/config/hooks'
make  distdir-am
make[9]: Entering directory '/root/git/retrace-server/src/config/hooks'
make[9]: *** No rule to make target 'mock.conf', needed by 'distdir-am'.  Stop.
make[9]: Leaving directory '/root/git/retrace-server/src/config/hooks'
make[8]: *** [Makefile:407: distdir] Error 2
make[8]: Leaving directory '/root/git/retrace-server/src/config/hooks'
=> Fix build error after change of mock.conf to environment.conf

src/retrace-server-reposync
See:
https://docs.python.org/3/library/functools.html#functools.cmp_to_key
=> r-s-reposync: Replace old way of cmp with key

src/retrace-server-reposync-faf
package_from_rpm() tried to create the packages using relative paths
(`../../../spool/faf/lob/xyz`), which is bogus.
The relative path is needed when retrace-server tries to install the
rpms later.
The path is then `/v/c/r-s/fedora/../../../spool/faf/lob/xyz/` - this works*.
=> r-s-reposync-faf: Fix paths to rpms

src/retrace-server-cleanup.txt, src/retrace-server-interact.txt, src/retrace-server-task.txt
There are a few omissions from the retrace-server-interact and
retrace-server-cleanup man pages. Add the missing information
which includes details on the set-success and set-fail options
for retrace-server-cleanup. Pointed to the OPTIONS section for
available switches for set and get parameters for
retrace-server-interact.
Signed-off-by: Audra Baker <aubaker@redhat.com>
=> Fix retrace-server-interact and retrace-server-cleanup man pages

DEPLOYING.md, retrace-server.spec.in, src/config/retrace-server.conf, src/retrace/config.py.in, src/retrace/retrace.py, src/retrace/retrace_worker.py
This PR uses the existing mechanisms currently used for mock config to create a Dockerfile in the crash directory. This is then used to create a podman container into which the coredump and metadata and a `gdb.sh` script are copied and where the retrace itself is run. The use of podman is optional and enabled by setting the newly introduced `RetraceEnvironment` config variable to `"podman"`. Changes to the `retrace` user are required during deployment in order to run retrace in a podman container, as described in  DEPLOYING.md.
=> Run retrace in a podman container instead of mock

src/retrace/retrace.py
If an unknown error occurs the following cryptic error is thrown:
[2020-01-29 17:11:52] [I] Searching for kernel-debuginfo package for 2.6.32-504.el6.x86_64
[2020-01-29 17:11:52] [E] not enough arguments for format string
The intent was to print out more info about the exception, and
fixing this bug shows better info:
[2020-01-29 17:30:15] [I] Searching for kernel-debuginfo package for 2.6.32-504.el6.x86_64
[2020-01-29 17:30:15] [W] crash command: 'mod; quit' triggered Unknown exception stdin and input arguments may not both be used.
[2020-01-29 17:30:15] [W]   <class 'ValueError'>
[2020-01-29 17:30:15] [E] prepare_debuginfo failed: 'NoneType' object has no attribute 'decode'
=> Fix error handling when unknown exception occurs in run_crash_cmd

src/retrace/retrace.py
Seems like this 991b9e4a5567eb2f3bd8570087e7d9b42ad1eb91 didn't fix it
properly.
=> retrace: Fix bytes has no attribute encode

src/plugins/centos.py, src/plugins/rhel.py
The release version is no longer just a simple number.
CentOS:
`CentOS Linux release 7 (Core)`
`CentOS Linux release 8.1.1234 (Core)`
RHEL:
`Red Hat Enterprise Linux release 8.1 (Ootpa)`
`Red Hat Enterprise Linux release 8.2 Beta (Ootpa)`
`Red Hat Enterprise Linux Server release 7.8 Beta (Maipo)`
https://regex101.com/
=> Update regexes for CentOS and RHEL releases

src/create.wsgi, src/retrace/Makefile.am, src/retrace/retrace.py, src/retrace/retrace_worker.py, src/retrace/stats.py, src/settings.wsgi, src/stats.wsgi
Tidies up the retrace.py a little bit.
No reason why to keep the crashstats functions in there.
A step towards issue #89
=> retrace: Split off crashstats related functions

src/coredump2packages
A change was introduced in Fedora 27 to allow for installing multiple versions of debuginfo packages in parallel. In effect, `/usr/lib/.build-id` may contain debug files, as well, in addition to `/usr/lib/debug/.build-id`.
See fedoraproject.org/wiki/Changes/ParallelInstallableDebuginfo for more details.
Related: abrt/abrt#1462, abrt/libreport#606, abrt/faf#894
=> c2p: Accommodate for multiple debug directories

src/backtrace.wsgi, src/checkpackage.wsgi, src/create.wsgi, src/delete.wsgi, src/exploitable.wsgi, src/ftp.wsgi, src/index.wsgi, src/log.wsgi, src/manager.wsgi, src/retrace-server-reposync, src/retrace/Makefile.am, src/retrace/__init__.py, src/retrace/config.py.in, src/retrace/retrace.py, src/retrace/retrace_worker.py, src/retrace/stats.py, src/retrace/util.py, src/settings.wsgi, src/start.wsgi, src/stats.wsgi, src/status.wsgi
The goal of this commit is to free `retrace.py` from stuff that
can be placed elsewhere (`util.py`) and make it more structured.
Most of the moved functions in this commit are never used in `retrace.py`.
=> retrace: Move stuff from retrace to util

autogen.sh
When a user passes 'sysdeps --install' to autogen.sh this will stop
with a prompt today and there's no way to run unattended.
=> Add '-y' to autogen.sh option to install dependencies without prompting

src/manager.wsgi
Commit 53fd9b5 reworked the parsing of manager page and missed
a subtle change for null values.  By default the 'start' method
passes some of the parameters such as 'kernelver' with null values:
start?kernelver=&caseno=&bugzillano=&notify=&debug=on&md5sum=on
This results in the following error message if 'kernelver' is not
filled in:
Please use VRA format for kernel version (e.g. 2.6.32-287.el6.x86_64)
Fix this by checking for null values in kernelver, caseno, and
notify.
=> Fix manager page ftp submission due to missing check for values

src/retrace-server-reposync
The cachedir property of Repo in DNF was made “private” in
62fcedbf32b9f0419dc4fcb9620860d51f4ffb29, largely due to $REASONS.
Following some more development since then, there is simply no way to
access the cache directory for individual repositories anymore (we
actually have correct code already, but this particular bit was missed).
The solution is to grab the base for cache and concatenate it with the
ID of the repository.
=> reposync: Stop accessing cachedir attribute of Repo objects

po/retrace-server.pot, src/create.wsgi, src/manager.wsgi, src/retrace-server-bugzilla-query, src/retrace-server-bugzilla-refresh, src/retrace-server-cleanup, src/retrace-server-interact, src/retrace-server-plugin-checker, src/retrace-server-reposync, src/retrace-server-reposync-faf, src/retrace-server-task, src/retrace/hooks/config.py, src/retrace/hooks/hooks.py, src/retrace/plugins.py, src/retrace/retrace.py, src/retrace/retrace_worker.py, src/retrace/util.py, test/run_test.py
This PR replaces (mostly) the `path` functions from the `os` module with their equivalents from `pathlib` in a (rather feeble) attempt to make the code more readable, especially awkward constructs lilke 'os.path.join`.  
This is probably a lot less useful than I thought originally, so feel free to suggest complete rewrites or just dumping this completely. I figure it might potentially have some sort of an impact in the future if/when stricter type checking is introduced with the [typing module](https://docs.python.org/3/library/typing.html).   
Thorough testing is still needed.
=> Replace os.path functions with their pathlib equivalents

src/retrace-server-task
python-requests strongly prefers header values to be strings and nothing
else these days.
Fixes https://github.com/abrt/retrace-server/issues/262
=> retrace-server-task: Stringify HTTP headers

src/retrace/retrace_worker.py
Again, strings are not paths.
Fixes https://github.com/abrt/retrace-server/issues/327
=> retrace_worker: Fix types

src/retrace/retrace.py
More fallout from https://github.com/abrt/retrace-server/pull/310
Also added some type annotations for easier future checks
Resolves:
https://github.com/abrt/retrace-server/issues/334
Signed-off-by: Michal Fabik <mfabik@redhat.com>
=> retrace: Check write() args to be str's

src/config/retrace-server.conf, src/retrace-server-interact, src/retrace/config.py.in, src/retrace/retrace.py, src/retrace/retrace_worker.py
These patches remove the old set_mock() / get_mock() logic that was used to allow 32-bit crash to run on a 64-bit machine.  This is not used anymore and was fairly ugly code.
In addition, this adds a "native" mode to "RetraceEnvironment" config variable which is the ability to run on the native machine, not in mock or podman.  This mode is used for interactive mode of retrace-server for vmcores, but is not used for userspace coredumps.
Finally, we add a "KernelDebuggerPath" config option.  This allows us to set the path to crash to be some non-system path which we can build and deploy to, and cleans up the hardcoded path.
=> Clean up logic for mock and vmcores and add configurable debugger path option

src/retrace/retrace.py
Before this patch, retrace-server-worker --restart command fails with
[E] 'NoneType' object has no attribute 'split'
Fix the above by making sure an exising task has a 'crash_cmd' file
and if not, write a default one.
=> retrace: Fix error when restarting a task with retrace-server-worker

man/retrace-server-task.txt, src/manager.wsgi, src/retrace-server-task, src/retrace-server-task.txt, src/retrace-server-worker, src/retrace/retrace.py, src/retrace/retrace_worker.py
It makes more sense to use retrace-server-task to restart a task the
same way we create a task.  In this way, we avoid numerous problems
with user credentials such as storing task files with user ownership
as well as issues with extracting kernel-debuginfos.
Fixes https://github.com/abrt/retrace-server/issues/346
=> retrace: Add restart to retrace-server-task to restart an existing task

src/retrace-server-task.txt
3f46464be80fecfb2c1cda262f2fdd3ad23f3ac2 removed the symlink to
man/retrace-server-task.txt, which was added to retain compatibility for
Autotools builds.
=> Add back symlink to retrace-server-task.txt

src/retrace/retrace.py
Somewhere along the line the Exception string failed to format
properly and the following cryptic error message would be thrown
on a crash command that exceeded ProcessCommunicateTimeout:
[E] not all arguments converted during string formatting
After this patch we get back the more informative message:
[E] WARNING: crash command: 'log; quit; ' exceeded 60  second timeout - damaged vmcore?
=> retrace: fix timeout exception error message in run_crash_cmdline

src/retrace/retrace_worker.py
Commit 8d0469b converted some strings to Path and path methods and
used 'link_to' which is a method added only in Python 3.8.  As a
result, retrace-server-cleanup would backtrace with the following
==> /var/log/retrace-server/cleanup_error.log-20200805 <==
total_savings += worker.dedup_vmcore(md5_tasks[md5])
File "/usr/lib/python3.6/site-packages/retrace/retrace_worker.py", line 627, in dedup_vmcore
v2_link.link_to(v1)
AttributeError: 'PosixPath' object has no attribute 'link_to'
File "/usr/bin/retrace-server-cleanup", line 145, in <module>
total_savings += worker.dedup_vmcore(md5_tasks[md5])
File "/usr/lib/python3.6/site-packages/retrace/retrace_worker.py", line 627, in dedup_vmcore
v2_link.link_to(v1)
AttributeError: 'PosixPath' object has no attribute …
=> retrace_worker: fix worker.dedup_vmcore due to missing Path.link_to

.github/workflows/check.yml, .gitignore, mypy.ini, src/coredump2packages, src/retrace-server-bugzilla-query, src/retrace-server-cleanup, src/retrace-server-interact, src/retrace-server-plugin-checker, src/retrace-server-reposync-faf, src/retrace-server-task, src/retrace/hooks/hooks.py, src/retrace/plugins.py, src/retrace/retrace.py, src/retrace/retrace_worker.py, src/retrace/stats.py, src/retrace/util.py
Following up to #352
Resolves #347
=> More type annotations and error fixing

src/retrace/retrace.py
We do not specify encoding when reading the log file. This causes
https://github.com/abrt/retrace-server/issues/364
I wonder if we should use utf-8 hardcoded or first try the environment settings and fall back to utf-8 if it does not work.
What do you guys think?
=> retrace: Open log files with utf-8 encoding

src/retrace-server-interact, src/retrace-server-reposync, src/retrace-server-task
If `retracer-server-task` cannot connect to the (default) `localhost` server, it falls back to retrace.fedoraproject.org, but does not check if it's able to connect there.
The problem is that it falls back to retrace.fp.org if the connection fails for any reason. Specifically, it falls back even if authentication fails on localhost.
Moreover, if retrace.fp.org is inacessible as well, we get an exception later down the road when trying to send an HTTP request.
In this change, we check if the server responded HTTP 401 Unauthorized, which should be the case if a valaid Kerberos ticket was expected by the server but not sent by the client.
Plus fix some code style issues reported by Pylint.
=> Fix crash if Kerberos authentication fails

src/retrace-server-reposync
`retrace-server-reposync` was failing on a misused `/` (path concatenation operator) due to dir keys in `CONFIG` being ordinary strings, not `Path`s. This commit fixes this and removes one redundant use of `/`, for more consistency.
=> retrace-server-reposync: Fix path concatenation error

man/retrace-server-task.txt, src/manager.wsgi, src/retrace-server-task, src/retrace/retrace_worker.py
Commit 6bf02a8 implemented a 'restart' option on the retrace-server-task
command, but did not implement all options which would be appropriate
for restart.  Add options options email, caseno, bugzillano, and md5sum.
Since these options are the same as when we 'start' a new task, refactor
the manager code on the backend to avoid parsing duplication.
=> retrace-server-task: Add options to restart command similar to create

docker/Dockerfile
With `COPY . /src` in the `Dockerfile` it assumed that `origin`
was pointing to `https://github.com/abrt/retrace-server.git`.
If that wasn't true (like in my case, `origin=git@github.com:abrt/retrace-server.git`)
tito build didn't have permissions (ssh key) to check the remote repo
and failed with Tag does not exist in remote git repo.
=> dockerfile: Fix build stage

src/coredump2packages, src/retrace-server-bugzilla-query, src/retrace-server-bugzilla-refresh, src/retrace-server-cleanup, src/retrace-server-interact, src/retrace-server-plugin-checker, src/retrace-server-reposync, src/retrace-server-reposync-faf, src/retrace-server-task
The `tmpdir` variable was accidentally left unchanged in [b6400d45](https://github.com/abrt/retrace-server/commit/b6400d45d6b94445840f40cbf1ce0b00c2b1f398), resulting in an error when trying to create the `temp` directory under `RepoDir`.  
Also, resolve some pylint issues.
=> retrace-server-reposync: Create cachedir as <RepoDir>/temp

src/create.wsgi
This fixes the error "Crash directory does not contain required file 'coredump'".
The bug was introduced in 94a71c2 during the transition to pathlib.
=> create: Fix type error

DEPLOYING.md, autogen.sh
`autogen.sh` does not support the `--install-dnf` option, don't mention it in the documentation.
=> Remove mentions of unsupported autogen option from documentation

src/backtrace.wsgi, src/checkpackage.wsgi, src/create.wsgi, src/delete.wsgi, src/exploitable.wsgi, src/ftp.wsgi, src/index.wsgi, src/log.wsgi, src/manager.wsgi, src/retrace/argparser.py, src/retrace/hooks/config.py, src/retrace/hooks/hooks.py, src/settings.wsgi, src/start.wsgi, src/stats.wsgi, src/status.wsgi
Install was giving this error which indicated /bin/python3 was
not provided:
Error:
Problem: conflicting requests
- nothing provides /bin/python3 needed by retrace-server-1.21.0-1.git.1011.3e498e3.el8.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
=> hooks: Change path to python interpreter from /bin to /usr/bin

.packit.yml
The `dist_git_branch` key has been renamed to `dist_git_branches` (plural) in Packit [0.10.1](https://github.com/packit/packit/blob/master/CHANGELOG.md#0101). Update our config accordingly.
=> Update Packit config

src/coredump2packages
* Call the `main()` function in `coredump2packages`. The refactor in 81e750f failed to ever call the function.
* Only look for binary packages with same architecture as debuginfo packages.
This should fix many of the recent retracing failures.
=> Repair coredump2packages

src/ftp.wsgi, src/manager.wsgi, src/manager.xhtml, src/manager_usrcore_task_form.xhtml, src/manager_vmcore_task_form.xhtml, src/managertask.xhtml
These changes rework the manager page to be a bit cleaner.  I though of going further with these, such as adding a small navigation bar on the left side of the page, but I think this is enough for now.
Short list of changes:
1. "FTP files" list removed from the first page, added link at the top
* FTP based vmcore file tasks are very low utilization now
* It takes time to load the page and probably does not make sense to have this on the front page
* This was always somewhat of a hack - if you reload the page you'll see a "Available tasks" table header pop up briefly before "FTP files"
2. Add border around the "Create vmcore task" area
3. Make "Finished Tasks" take up the full page.
* Previously the page was split, and a lot of space was wasted
* Now "Running Tasks" and "Available Tasks" …
=> Rework manager page

src/plugins/fedora.py, src/retrace-server-reposync-faf
Second round of fixes for recent retrace server problems:
* Update Fedora plugin version list: Add F33 and remove versions older than F31.
* Fix type errors in `retrace-server-reposync-faf`.
=> Fix reposync; update Fedora version list

src/retrace/util.py
* Replace ranges with PCRE escapes, e.g. `a-zA-Z` → `\w`.
* Fix package name (NEV) parser to correctly handle epoch numbers. The epoch was previously assumed to be a prefix of the whole name (in ENV form), e.g. `1:findutils-4.7.0-4.fc33`. In order to be consistent with abrt, DNF and RPM, we switch to NEV form, that is `findutils-1:4.7.0-4.fc33`.
Potentially related: #400
=> Improve regexes for parsing problem data

src/retrace/retrace.py, src/retrace/util.py
* The changes in 84d67af made the regexes accept more inputs as valid than originally intended due to the use of `\w`, `\d`, etc. This commit changes the regexes to be equivalent to the previous state.
* Repair how epoch number is stripped from package designation in NEVR(A) form.
* Minor code style fixes.
Follow-up to #409
=> Regex repairs and epoch stripping fix

src/retrace-server-cleanup, src/retrace/retrace.py, src/retrace/util.py
* Time out and abort if Podman takes too long.
* Express elapsed process time in seconds.
* Check if crash directory exists before cleaning it up.
* Improve some regular expressions.
* Various minor Pythonic style improvements.
Resolves #394
=> retrace and r-s-cleanup improvements

src/retrace/retrace.py
When iterating over some directories found in the crashdir,
retrace was trying to move the "fullpath" (i.e. the original
file) instead of "file_path" (the directory), and the task
would fail with the following message:
[2021-02-04 10:52:48] [E] Task failed: [Errno 2] No such file or
directory: '/cores/retrace/tasks/231067672/crash/testfile-vmcore'
Signed-off-by: Pierguido Lambri <plambri@redhat.com>
Reviewed-by: Dave Wysochanski <dwysocha@redhat.com>
=> retrace: Fix "file not found" when the archive contains directories

src/retrace/retrace.py, src/retrace/retrace_worker.py
With this we log the exception backtrace in addition to the normal
error message when debug is enabled. This may be helpful when troubleshooting
some issues where it's not clear where the error comes from.
For example, before applying this patch we would get this error:
[2021-02-04 10:52:48] [E] Task failed: [Errno 2] No such file or
directory: '/cores/retrace/tasks/231067672/crash/testfile-vmcore'
Now we get this error plus backtrace:
[2021-02-05 07:00:42] [E] Task failed: [Errno 2] No such file or directory: '/cores/retrace/tasks/889893066/crash/testfile-vmcore'
[2021-02-05 07:00:42] [D] Backtrace: [Errno 2] No such file or directory: '/cores/retrace/tasks/889893066/crash/testfile-vmcore'
File …
=> retrace_worker: Add backtrace to log when a task fails with error

retrace-server.spec, src/retrace-server-reposync, src/retrace-server-reposync-faf, src/retrace/backends/meson.build, src/retrace/backends/podman.py, src/retrace/config.py.in, src/retrace/meson.build, src/retrace/retrace.py, src/retrace/retrace_worker.py
These changes entail a complete refactoring of the Podman-based retracing backend. The biggest change is that only one container image is now built for each release (e.g. Fedora 32, Fedora 33, etc.) with basic tools preinstalled (abrt-addon-ccpp and GDB) and new containers are run from this base image on demand.
Some more changes are made for improving readability and maintainability.
See commits for details.
This code is currently deployed and ready for experimenting at <https://retrace-stg.aws.fedoraproject.org/> (only Fedora 33 supported).
Should fix at least [rhbz#1922471](https://bugzilla.redhat.com/show_bug.cgi?id=1922471) and [rhbz#1932768](https://bugzilla.redhat.com/show_bug.cgi?id=1932768).
=> Podman backend refactor and fixes

src/backtrace.wsgi, src/delete.wsgi, src/exploitable.wsgi, src/manager.wsgi, src/retrace-server-plugin-checker
A bare `except:` statement catches all exception inheriting from `BareException` including `SystemExit` and `KeyboardInterrupt`. That is rarely what we want and whenever we do, we should be explicit about that and handle each case separately.
Problem pointed out by LGTM.
=> Fix bare `except` occurrences

src/retrace/util.py, test/meson.build, test/test_util.py
Adjust the `human_readable_size` function to print 1024 bytes as 1.00 kB intead of 1024.00 B.
Also testing the code coverage reporting setup.
=> util: Print 1024 bytes as 1.00 kB

doc/retrace-server.texi, src/create.wsgi, src/manager.wsgi, src/retrace-server-interact, src/retrace-server-task, src/retrace/retrace.py, src/retrace/retrace_worker.py
In retrace-server there are userspace coredumps and kernel vmcores.
The kernel vmcores have tasks identified by TASK_VMCORE and
TASK_VMCORE_INTERACTIVE.  However, userspace coredumps are
identified with TASK_RETRACE and TASK_RETRACE_INTERACTIVE,
which is inconsistent and ambigous.  Thus, rename TASK_RETRACE
and TASK_RETRACE_INTERACTIVE to TASK_COREDUMP and
TASK_COREDUMP_INTERACTIVE.  In addition, correct one typo
in doc/retrace-server.texi.
=> Replace TASK_RETRACE with TASK_COREDUMP for consistency

.github/workflows/coverage.yml, meson.build, retrace-server.spec, src/retrace/meson.build, test/meson.build
Make sure the spec file is in the build directory so that Tito can run the `rpm` and `srpm` targets.
=> meson: Copy spec file to build directory

src/retrace-server-interact
Its possible for a user to be in a group that does not have a name.
In this case retrace-server-interact will Traceback something like
the following
File "/usr/bin/retrace-server-interact", line 31, in <module>
groups = [grp.getgrgid(g).gr_name for g in os.getgroups()]
File "/usr/bin/retrace-server-interact", line 31, in <listcomp>
groups = [grp.getgrgid(g).gr_name for g in os.getgroups()]
KeyError: 'getgrgid(): gid not found: 12345'
Fix this by ensuring we don't assume the group database will
have an entry for each gid, in which case getgrgid() will raise
KeyError.  If this happens, catch the exception and just skip
over the gid.
=> retrace-server-interact: Fix traceback for non-existent gid

src/config/retrace-server.conf, src/manager.wsgi, src/retrace-server-cleanup, src/retrace/config.py.in, src/retrace/hooks/hooks.py, src/retrace/retrace.py, src/retrace/retrace_worker.py, src/retrace/util.py
As https://bugzilla.redhat.com/show_bug.cgi?id=2049284 explains,
makedumpfile can infinite loop similar to what has previously
happened with crash.  With makedumpfile, such a loop can have
impacts beyond just CPU usage, and as was seen in the above bug,
all free disk space may fill up and thus have larger impacts.
To resolve this issue, first, re-use the same config setting,
CONFIG["ProcessCommunicateTimeout"], for makedumpfile as we
did for crash in commit becb40663a003.  Second, increase the
default value of CONFIG["ProcessCommunicateTimeout"] to reflect
a more realistic "worst case" valid runtime.  In production we
have seen makedumpfile may run up to 6 hours on some larger
vmcores.  Given various filesystems performance characteristics
and to add some margin, set the default of …
=> retrace: Re-use ProcessCommunicateTimeout with makedumpfile

src/config/retrace-server.conf, src/retrace/config.py.in, src/retrace/retrace.py, src/retrace/retrace_worker.py
Currently we do not check to see if running makedumpfile and creating a stripped vmcore is actually worthwhile. In some situations we may see little to no benefit to stripping down a vmcore and replacing the original with the newly stripped vmcore. For those situation, this patch adds the config variable SpaceSavePercent which is meant to indicate the percentage of space a stripped vmcore will need to save for us to choose to save it in place of the original. The proposed default is 10%. This patch also adjusts the logic so that the relevant message about makedumpfile will be printed (i.e. if makedumpfile is not run or we don't use the stripped vmcore from makedumpfile we do not print how much space we saved).
Signed-off-by: Audra Mitchell <aubaker@redhat.com> #445
=> Add logic to determine if we save a stripped vmcore

src/manager_usrcore_task_form.xhtml, src/manager_vmcore_task_form.xhtml
The POST actions on the manager page to submit a custom vmcore
or coredump should be protected from double clicks which can
cause tasks to be created but never started and end up stuck
in "available" state.  Fix this by disabling the button on
submission.
Fixes: https://github.com/abrt/retrace-server/issues/446
=> manager: Prevent double submit of vmcore or coredump tasks

meson.build, retrace-server.spec, src/retrace/archive.py, src/retrace/config.py.in, src/retrace/meson.build
If 'unar' tool is installed we can extract 'rar' archives, which
is a rare, but not non-existent, archive type.
Make this an optional install for meson to prevent build failures.
If not installed, but a RAR archive is submitted, the task will
fail with something like the following in retrace_log:
[D] File type: rar archive data, v4, os: win32
[D] rar detected
[W] [Errno 2] No such file or directory: 'unar': 'unar'
Resolves: https://github.com/abrt/retrace-server/issues/465
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1457434
=> config: Add support for RAR archives if the unar tool is installed

src/retrace/hooks/config.py
We had an instance in production where a user's home directory was unable
to be accessed and returned "permission denied".  This also had the effect
of a Traceback if a user tried "retrace-server-task create" or even
"retrace-server-interact", since the hooks path failed with permission
denied per below.  Fix the Traceback by wrapping pathlib.exist() checks
in try .. except clauses.
Before the patch:
$ retrace-server-interact 846035327 crash
File "/usr/bin/retrace-server-interact", line 12, in <module>
from retrace.retrace import (ALLOWED_FILES,
File "/usr/lib/python3.6/site-packages/retrace/__init__.py", line 18, in <module>
from . import retrace_worker
File "/usr/lib/python3.6/site-packages/retrace/retrace_worker.py", line 16, in <module>
from …
=> retrace: Fix Traceback if user's home directory is unavailable

src/retrace-server-task
It's not uncommon in production to have a certificate expire, and when that happens we use the FAILBACK_SERVER, but this is unlikely to be what the user wants.
This patch catches the error and gives the user possible next steps to avoid the error, similar to earlier commit cf85a18c1b29.
=> retrace-server-task: Add exception handling for SSLError

src/plugins/centos.py, src/plugins/rhel.py, src/stats.wsgi
The stats database has a 'version' field which records the version of the package.  The value of this field though may not end in the any of the strings listed in the plugins though.  For the kernel, the 'arch' value is included at the end of the value.  Also, for any z-stream package versions include the minor (Y) version after the major (X) version (for example, "el8_2" for a 8.2.0.z package). Fix these issues by using a wildcard at the end of the database query string.
In addition, add 'el9' to the 'rhel' and 'centos' plugins.
=> stats: Fix Releases counting by using wildcard at end and add el9

src/retrace/retrace.py
If AuthGroup is set in the config but getgrnam() fails for some reason (such as a network or server error) the below Traceback will occur.  Fix this by catching KeyError and handling the same as with OSError in chgrp.
Also if chrgrp fails, we don't want to continue so raise an exception here which should fail the task.
File "/usr/lib/python3.6/site-packages/retrace/retrace_worker.py", line 1102, in start
errors = task.download_remote()
File "/usr/lib/python3.6/site-packages/retrace/retrace.py", line 1199, in download_remote
self.set_md5sum("\n".join(md5sums)+"\n")
File "/usr/lib/python3.6/site-packages/retrace/retrace.py", line 1439, in set_md5sum
self.set(RetraceTask.MD5SUM_FILE, value)
File "/usr/lib/python3.6/site-packages/retrace/retrace.py", line …
=> retrace: Fix Traceback if getgrpnam() fails and fail task if chgrp fails

src/retrace/archive.py
The message to log 'not an archive' is of little to no value. In our production system we see this logged for every vmcore so it just takes up log space.  Also there is no message logged for coredumps so remove this message for vmcores.
=> retrace: Remove low value 'not an archive' message for vmcores
